
Vagrant.configure("2") do |config|
  config.vm.define "dapariciS" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = "dapariciS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "dapariciS"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end

  config.vm.define "dapariciSW" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = "dapariciSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "dapariciSW"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
end
